### ISSUE TITLE
vwebui does not re-use open browser (MacOS)

### ISSUE THREAD

**Issue by cyclecraze** [webui-dev/v-webui#13]
Running any example once a browser is open does not seem to work. Existing tab remains the same/blank, a new tab is not opened. The only thing that happens is for the browser to be brought into focus.

V full version: V 0.3.4 b9a8a21.134e781
OS: macos, macOS, 13.3.1, 22E261
Processor: 12 cpus, 64bit, little endian, Apple M2 Max

→ v show vwebui
Name: vwebui
Version: 2.2.0
Description: Use any web browser as GUI, with V in the backend and HTML5 in the frontend, all in a lightweight portable lib.
Homepage: https://github.com/malisipi/vwebui
Author: Mehmet Ali
License: GPL-3.0

**Comment by AlbertShown** [comment]
Yes. Unfornantly this issue exists on macOS.
It's a [known issue](https://github.com/alifcommunity/webui/issues/69#issuecomment-1521060101).

**What happens?**
When you run the program the first time, it will work, and the second run will show the home page.

**Workaround**
It will fix if you quit Chrome using the top left menu.

**Problem**
Run this command: `open -W "/Applications/Google Chrome.app" --args --user-data-dir="/Users/mtt/.WebUI/WebUIChromeProfile" --no-first-run --disable-gpu --disable-software-rasterizer --no-proxy-server --safe-mode --disable-extensions --disable-background-mode --disable-plugins --disable-plugins-discovery --disable-translate --bwsi --disable-sync --app=https://www.wikipedia.org/ >>/dev/null 2>>/dev/null`.

Just copy and paste this command into your terminal, run (_You will see Wikipedia_), close the window [X] (_normal close_), then run the command again. You will probably see the home page instead of Wikipedia.

**Solution**
We need to tweak the command arguments until we solve the issue.

If you find the best command arguments, please share them with us here. Here is a [list of Chromium commands](https://peter.sh/experiments/chromium-command-line-switches/).

**Comment by malisipi** [comment]
Can you try the latest version?

**Comment by cyclecraze** [comment]
Now, it always opens a new browser window, which is better.

**Comment by hassandraga** [comment]
This issue can be closed as fixed.
