### ISSUE TITLE
fatal error: client/webui.h: No such file or directory

### ISSUE THREAD

**Issue by mmertgunduz** [webui-dev/v-webui#31]
#### I was trying to build the program by using this method:

```
git clone https://github.com/webui-dev/webui.git
cd webui/build/Linux/GCC
make
make debug
```
<hr>

#### But it gave me this error:

![image](https://github.com/webui-dev/v-webui/assets/65850970/c738d417-edb2-47ed-8e1d-77939a10f5ce)

Is there a way to solve this problem?

Thanks,
**_Mehmet Mert_**

**Comment by mmertgunduz** [comment]
![image](https://github.com/webui-dev/v-webui/assets/65850970/110d7a09-e8f7-4b31-93a0-3d69c1df55d9)

<hr>

#### Also, opened the vscode to the source directory and had this error:

```
[{
	"resource": "/home/mehmetmertgunduz/webui/src/webui.c",
	"owner": "C/C++: IntelliSense",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"client/webui.h\"",
	"source": "C/C++",
	"startLineNumber": 19,
	"startColumn": 1,
	"endLineNumber": 19,
	"endColumn": 26
}]
```

**Comment by ttytm** [comment]
Since you are posting in the `v-webui` issues and the trend is that the core library will be integrated as a pre-built, I can suggest something that you could try as a quick-fix until the integration is complete. 

This PR integrates it #27. So you could check out the PR branch (e.g., if you have git cli installed `gh pr checkout 27`) and try to run an example e.g., `v run examples/minimal.v` and see if it compiles for you.

**Comment by AlbertShown** [comment]
Related with https://github.com/webui-dev/webui/issues/139

**Comment by mmertgunduz** [comment]
> Since you are posting in the `v-webui` issues and the trend is that the core library will be integrated as a pre-built, I can suggest something that you could try as a quick-fix until the integration is complete.
> 
> This PR integrates it #27. So you could check out the PR branch (e.g., if you have git cli installed `gh pr checkout 27`) and try to run an example e.g., `v run examples/minimal.v` and see if it compiles for you.

Thanks a lot tobe, will try that.
